@WebhookInbox_HostAddress = http://localhost:5282

GET {{WebhookInbox_HostAddress}}/health/
Accept: application/json

###
POST {{WebhookInbox_HostAddress}}/api/events
Content-Type: application/json

{
  "source": "github",
  "eventType": "push",
  "payload": "{\"ref\":\"refs/heads/main\"}"
}

###
GET {{WebhookInbox_HostAddress}}/api/events
Accept: application/json

###
@id = 450da462-8fde-4d72-b88b-24688ca97727
GET {{WebhookInbox_HostAddress}}/api/events/{{id}}
Accept: application/json

###
DELETE {{WebhookInbox_HostAddress}}/api/events/{{id}}
