@WebhookInbox_HostAddress = http://localhost:5282

GET {{WebhookInbox_HostAddress}}/health/
Accept: application/json

###
POST {{WebhookInbox_HostAddress}}/api/events
Content-Type: application/json

{
  "source": "github",
  "eventType": "push",
  "payload": "{\"ref\":\"refs/heads/main\"}"
}

###
GET {{WebhookInbox_HostAddress}}/api/events
Accept: application/json

###
GET {{WebhookInbox_HostAddress}}/api/events/305cdc14-7287-48cc-afc5-66208234dbd
Accept: application/json
